datasets:
  # List any number of train directories here (ContrastiveImageDataset will be applied to each).
  # NNI/your script will iterate through each path and concatenate them.
  train_dirs:
    - "../data/lfw-deepfunneled"
    - "../data/CelebA"
    # - "../data/CASIA-maxpy-clean"    # <-- you can add more if desired

  # Exactly one test directory for evaluation (AlbumentationsImageDataset).
  test_dir: "../data/CFP_dataset"

pretrained:
  weights_path: "../models_weights/representation/20180402-114759-facenet.pt"

dataloader:
  num_workers: 2

scheduler:
  eta_min: 1e-7

logging:
  log_dir_prefix: "logs/"

hyperparameters:
  batch_size: 1024
  learning_rate: 0.0003
  num_epochs: 200
  first_stage_epochs: 20
  weight_decay: 1e-5
  temperature: 0.1

loss:
  margin: 28.6
  scale: 64

model:
  embedding_size: 512